const adminActionTypes = {
    LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
    LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
    LOGIN_FAILURE: "ADMIN_LOGIN_FAILURE",

    LOGOUT_REQUEST: "ADMIN_LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "ADMIN_LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "ADMIN_LOGOUT_FAILURE",

    GET_EVENTS_REQUEST: "GET_EVENTS_REQUEST",
    GET_EVENTS_SUCCESS: "GET_EVENTS_SUCCESS",
    GET_EVENTS_FAILURE: "GET_EVENTS_FAILURE",

    GET_PARTICIPANTS_REQUEST: "GET_PARTICIPANTS_REQUEST",
    GET_PARTICIPANTS_SUCCESS: "GET_PARTICIPANTS_SUCCESS",
    GET_PARTICIPANTS_FAILURE: "GET_PARTICIPANTS_FAILURE",

    PROMOTE_PARTICIPANTS_REQUEST: "PROMOTE_PARTICIPANTS_REQUEST",
    PROMOTE_PARTICIPANTS_SUCCESS: "PROMOTE_PARTICIPANTS_SUCCESS",
    PROMOTE_PARTICIPANTS_FAILURE: "PROMOTE_PARTICIPANTS_FAILURE",

    SELECT_STUDENT_REQUEST: "SELECT_STUDENT_REQUEST",
    SELECT_STUDENT_SUCCESS: "SELECT_STUDENT_SUCCESS",
    SELECT_STUDENT_FAILURE: "SELECT_STUDENT_FAILURE",

    SHORTLIST_STUDENT_REQUEST: "SHORTLIST_STUDENT_REQUEST",
    SHORTLIST_STUDENT_SUCCESS: "SHORTLIST_STUDENT_SUCCESS",
    SHORTLIST_STUDENT_FAILURE: "SHORTLIST_STUDENT_FAILURE",

    GET_STUDENTS_REQUEST: "GET_STUDENTS_REQUEST",
    GET_STUDENTS_SUCCESS: "GET_STUDENTS_SUCCESS",
    GET_STUDENTS_FAILURE: "GET_STUDENTS_FAILURE",

    UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
    UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",

    AVATAR_REQUEST: "AVATAR_REQUEST",
    AVATAR_SUCCESS: "AVATAR_SUCCESS",
    AVATAR_FAILURE: "AVATAR_FAILURE",

    GET_AVATAR_REQUEST: "GET_AVATAR_REQUEST",
    GET_AVATAR_SUCCESS: "GET_AVATAR_SUCCESS",
    GET_AVATAR_FAILURE: "GET_AVATAR_FAILURE",

    REGISTER_THROUGH_CSV_REQUEST: "REGISTER_THROUGH_CSV_REQUEST" ,
    REGISTER_THROUGH_CSV_SUCCESS: "REGISTER_THROUGH_CSV_SUCCESS" ,
    REGISTER_THROUGH_CSV_FAILURE: "REGISTER_THROUGH_CSV_FAILURE" ,

    TOGGLE_EVENT_STATUS_REQUEST: "TOGGLE_EVENT_STATUS_REQUEST",
    TOGGLE_EVENT_STATUS_SUCCESS: "TOGGLE_EVENT_STATUS_SUCCESS",
    TOGGLE_EVENT_STATUS_FAILURE: "TOGGLE_EVENT_STATUS_FAILURE",

    GET_EVENT_STATUS_REQUEST: "GET_EVENT_STATUS_REQUEST",
    GET_EVENT_STATUS_SUCCESS: "GET_EVENT_STATUS_SUCCESS",
    GET_EVENT_STATUS_FAILURE: "GET_EVENT_STATUS_FAILURE",
};
export default adminActionTypes;
